### ISSUE TITLE
Not getting any tts output from TS3

### ISSUE THREAD

**Issue by WorldofShadows** [Flakebi/ts3tts#1]
Hey!

thank you for your work on updating the ts3 library.
I could finally compile ts3tts and the library is loaded by my ts3 client, but i can't get ts3 to output any tts-sound and i feel somehow lost why.

Would appreciate your help with this, if possible :)

I got some warnings while running cargo build --release

> 
> warning: no edition set: defaulting to the 2015 edition while the latest is 2021
>    Compiling proc-macro2 v1.0.87
>    Compiling unicode-ident v1.0.13
>    Compiling memchr v2.7.4
>    Compiling libc v0.2.159
>    Compiling byteorder v1.5.0
>    Compiling cfg-if v1.0.0
>    Compiling regex-syntax v0.8.5
>    Compiling siphasher v0.3.11
>    Compiling autocfg v1.4.0
>    Compiling thiserror v1.0.64
>    Compiling crossbeam-utils v0.8.20
>    Compiling ucd-trie v0.1.7
>    Compiling log v0.4.22
>    Compiling same-file v1.0.6
>    Compiling unic-common v0.9.0
>    Compiling libm v0.2.8
>    Compiling serde v1.0.210
>    Compiling once_cell v1.20.2
>    Compiling unic-char-range v0.9.0
>    Compiling iana-time-zone v0.1.61
>    Compiling serde_json v1.0.128
>    Compiling itoa v1.0.11
>    Compiling deunicode v1.6.0
>    Compiling ryu v1.0.18
>    Compiling anyhow v1.0.89
>    Compiling bitflags v2.6.0
>    Compiling lazy_static v1.5.0
>    Compiling percent-encoding v2.3.1
>    Compiling unic-ucd-version v0.9.0
>    Compiling walkdir v2.5.0
>    Compiling unic-char-property v0.9.0
>    Compiling phf_shared v0.11.2
>    Compiling ts3plugin-sys v0.5.0
>    Compiling unic-ucd-segment v0.9.0
>    Compiling slug v0.1.6
>    Compiling phf v0.11.2
>    Compiling num-traits v0.2.19
>    Compiling unic-segment v0.9.0
>    Compiling aho-corasick v1.1.3
>    Compiling bstr v1.10.0
>    Compiling crossbeam-epoch v0.9.18
>    Compiling humansize v2.1.3
>    Compiling quote v1.0.37
>    Compiling getrandom v0.2.15
>    Compiling syn v2.0.79
>    Compiling crossbeam-deque v0.8.5
>    Compiling rand_core v0.6.4
>    Compiling chrono v0.4.38
>    Compiling regex-automata v0.4.8
>    Compiling zerocopy-derive v0.7.35
>    Compiling thiserror-impl v1.0.64
>    Compiling regex v1.11.0
>    Compiling globset v0.4.15
>    Compiling ignore v0.4.23
>    Compiling parse-zoneinfo v0.3.1
>    Compiling zerocopy v0.7.35
>    Compiling globwalk v0.9.1
>    Compiling pest v2.7.13
>    Compiling ppv-lite86 v0.2.20
>    Compiling rand_chacha v0.3.1
>    Compiling rand v0.8.5
>    Compiling pest_meta v2.7.13
>    Compiling phf_generator v0.11.2
>    Compiling phf_codegen v0.11.2
>    Compiling chrono-tz-build v0.3.0
>    Compiling chrono-tz v0.9.0
>    Compiling pest_generator v2.7.13
>    Compiling pest_derive v2.7.13
>    Compiling tera v1.20.0
>    Compiling ts3plugin v0.3.0
>    Compiling ts3tts v0.3.0 (/home/wolf/git/ts3tts)
> warning: unused `#[macro_use]` import
>  --> src/lib.rs:9:1
>   |
> 9 | #[macro_use]
>   | ^^^^^^^^^^^^
>   |
>   = note: `#[warn(unused_imports)]` on by default
> 
> warning: unused imports: `AsRawFd` and `FromRawFd`
>   --> src/lib.rs:12:26
>    |
> 12 | use std::os::unix::io::{ AsRawFd, FromRawFd };
>    |                          ^^^^^^^  ^^^^^^^^^
> 
> warning: unused variable: `api`
>    --> src/lib.rs:162:35
>     |
> 162 |     fn connection_info(&mut self, api: &TsApi, server: &Server,
>     |                                   ^^^ help: if this is intentional, prefix it with an underscore: `_api`
>     |
>     = note: `#[warn(unused_variables)]` on by default
> 
> warning: unused variable: `server`
>    --> src/lib.rs:162:48
>     |
> 162 |     fn connection_info(&mut self, api: &TsApi, server: &Server,
>     |                                                ^^^^^^ help: if this is intentional, prefix it with an underscore: `_server`
> 
> warning: unused variable: `connection`
>    --> src/lib.rs:163:2
>     |
> 163 |     connection: &Connection) {
>     |     ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_connection`
> 
> warning: unused variable: `api`
>    --> src/lib.rs:167:49
>     |
> 167 |     fn connection_properties_changed(&mut self, api: &TsApi, _: &Server,
>     |                                                 ^^^ help: if this is intentional, prefix it with an underscore: `_api`
> 
> warning: unused variable: `changes`
>    --> src/lib.rs:169:9
>     |
> 169 |         changes: ConnectionChanges, _: &Invoker) {
>     |         ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_changes`
> 
> warning: unused variable: `api`
>    --> src/lib.rs:275:37
>     |
> 275 |     fn connection_announced(&mut self, api: &TsApi, server: &Server,
>     |                                        ^^^ help: if this is intentional, prefix it with an underscore: `_api`
> 
> warning: unused variable: `server`
>    --> src/lib.rs:275:50
>     |
> 275 |     fn connection_announced(&mut self, api: &TsApi, server: &Server,
>     |                                                     ^^^^^^ help: if this is intentional, prefix it with an underscore: `_server`
> 
> warning: unused variable: `connection`
>    --> src/lib.rs:276:3
>     |
> 276 |         connection: &Connection, appeared: bool) {
>     |         ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_connection`
> 
> warning: unused variable: `appeared`
>    --> src/lib.rs:276:28
>     |
> 276 |         connection: &Connection, appeared: bool) {
>     |                                  ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_appeared`
> 
> warning: unused variable: `api`
>    --> src/lib.rs:280:38
>     |
> 280 |     fn connection_changed(&mut self, api: &TsApi, server: &Server,
>     |                                      ^^^ help: if this is intentional, prefix it with an underscore: `_api`
> 
> warning: unused variable: `api`
>    --> src/lib.rs:306:35
>     |
> 306 |     fn connection_move(&mut self, api: &TsApi, server: &Server,
>     |                                   ^^^ help: if this is intentional, prefix it with an underscore: `_api`
> 
> warning: unused variable: `api`
>    --> src/lib.rs:334:36
>     |
> 334 |     fn connection_moved(&mut self, api: &TsApi, server: &Server,
>     |                                    ^^^ help: if this is intentional, prefix it with an underscore: `_api`
> 
> warning: `ts3tts` (lib) generated 14 warnings (run `cargo fix --lib -p ts3tts` to apply 1 suggestion)
>     Finished `release` profile [optimized] target(s) in 11.31s

Runnning Arch with kernel 6.11.2-arch1-1 and KDE Plasma 6
TeamSpeak 3 3.6.2
espeak-ng 1.51.1-4 (creates a symlink to espeak and supports the full api of the old espeak)
alsa-utils 1.2.12-1

Setting "Default Text to Speech" in ts3 outputs no error, but playing test sounds result in Warnings in the ClientLog:

> 08.10.24 17:51:26	ClientUI	Warning	Failed to play test sound	
> 08.10.24 17:51:28	ClientUI	Warning	Failed to play test sound	
> 08.10.24 17:51:30	ClientUI	Warning	Failed to play test sound

espeak itself works fine in terminal.

Do you have any idea what i can try to get it work? Do i need to create a new soundpack?

Thanks in advance :)

EDIT: Used "quotes" for the messages, "code" doesn't work right, because of the cargo output

**Comment by Flakebi** [comment]
Ah, I forgot to update the readme. It doesn’t use `espeak` anymore, but `mimic`. See the code here: https://github.com/ReSpeak/ts3tts/blob/master/src/lib.rs#L96C60-L96C65
If you want to use `espeak` instead, here’s the diff that changed it: https://github.com/ReSpeak/ts3tts/commit/ad7b3408fc2ec634009e1f8bde2bed0f0b4f95af#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759

**Comment by WorldofShadows** [comment]
Oh, that explains it.
Since this is all new to me and the tts is solely for ts3, i'm really fine with mimic i think. :)
I tried to install it, but neither of the versions in the aur repository seem to work right. Mostly through package errors.
Can you tell me the right one here?

According to the mimic aur, the mimic dev recommends the successor, piper:
https://github.com/rhasspy/piper
I wonder if this could work just the same?

**Comment by Flakebi** [comment]
Piper should work similar to espeak, it outputs raw audio, which needs to be piped into `aplay` or `pw-play`.
Piper seems to use quite a bit more CPU than mimic from what I can tell.

I’m not using arch, so I don’t know the available packages there, but for reference, mimic 1.3.0.1 works for me ([package](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/mimic/default.nix)].

**Comment by WorldofShadows** [comment]
Fixed it, thank you :)
That was a journey.
Apparrently the one you use is called mimic1 over at Mycroftai (and the arch repo) and i had an error in my alsa/pipewire configs to begin with.
Now it works fine. 
Now i just need some good voice files and a bit of modification for the messages tts read for me, but i think i can figure that out. :)

I'll close the issue. Thank you for your help.
